########################################################################
--- Contributor 51814830 09AUG2019
--- This ymal is used to create aws ec2 instance
--- Create a security group
--- Create key pair and the PEM file
--- Create EC2 instance
---  Save the EC2 instance IP address to the ansible inventory file
--- ########################################################################
- hosts: all
  become: true
  #sudo: True
  gather_facts: False
#
  vars:
     region: us-west-2
     instance_type: t2.micro
     ami: ami-027386b91d3c0bf78
     hosts_file: /etc/ansible/hosts
     vpc_id: vpc-0f8433056baf07571
  tasks:
    - name: Create security group
      ec2_group:
         aws_access_key: AKIAIN363MYRALA35ONA
         aws_secret_key: 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
         name: "mm"
         description: "security group"
         vpc_id: "{{ vpc_id }}"
         region: "{{ region }}"
         rules:
           - proto: tcp
             from_port: 22
             to_port: 22
             cidr_ip: 0.0.0.0/0
#
    - name: Create an EC2 key
      ec2_key:
         aws_access_key: AKIAIN363MYRALA35ONA 
         aws_secret_key: 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
         name: "test machine"
         region: "{{ region }}"
         register: ec2_key
    - name: Save private key (PEM file)
      copy: content="{{ec2_key.key.private_key}}" dest=/home/ansi/mm.pem mode=0600
      when: ec2_key.changed
    - name: Create an ec2 instance
      ec2:
         aws_access_key: AKIAIN363MYRALA35ONA
         aws_secret_key: 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
         key_name: mm
         group: mm # security group name
         instance_type: "{{ instance_type }}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         vpc_id: "{{ vpc_id }}"
         count: 1 # default
         count_tag:
            Name: Demo
         instance_tags:
            Name: Demo
            register: ec2
    - name: Save IP to inventory file
      lineinfile:
         dest: "{{hosts_file}}"
         insertafter: '\[webservers\]'
         line: "{{item.private_ip}}"
         with_items: "{{ec2.instances}}"
