- hosts: cache
  user: ansi 
  sudo: yes
  tasks:
   - name: /etc/sysctl.conf
     lineinfile:
       dest: /etc/sysctl.conf
       regexp: "{{ item.regexp }}"
       line: "{{ item.line }}"
     with_items:
       - { regexp: '^overcommit_memory ', ' }
